config/routes.rb
Rails.application.routes.draw do
  
 
    
  resources :zutatens
  devise_for :users
  resources :reviews
  get 'orders/index'
  get 'reviews/index'
  get 'home/index'
  get 'home/about'

  root  'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    mount_uploader :image, ImageUploader
    serialize :image, JSON
    belongs_to :user, optional: true
    
    
    #checks if data was put into the text field
    validates :text, presence: true
    #checks if the length is within the paramers of the text
    validates :text, length: {maximum: 1000, too_long: "%[count] characters is the maximum allowed length. Please shorten it a bit"}
    
    #all given values for the Satisfaction
    SATISFACTION = %w{Perfect! Good. Ok. Alright. Not pleased.}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
    
    has_many :reviews
end

app/models/zutaten.rb
class Zutaten < ApplicationRecord
    mount_uploader :image, ImageUploader
    serialize :image, JSON
    belongs_to :user, optional: true
    
    
    #checks if data was put into the text field
    validates :name, presence: true
    #checks if the length is within the paramers of the text
    validates :name, length: {maximum: 50, too_long: "%[count] characters is the maximum allowed length. Please shorten it a bit"}
    
    #all given values for the Satisfaction
    validates :price,numericality: {only_integer: true}, length: {maximum:7}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 private

 def sign_up_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
 end

 def account_update_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
 end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

    before_action :authenticate_user!, except: [:index, :show]
    
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all.order("created_at desc")
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
   
    @review = current_user.reviews.build
    #@review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    
    @review = current_user.reviews.build(review_params)
    #falls das oben nicht geht, das hier benutzten  
    #@review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:text,:image)
    end
end

app/controllers/zutatens_controller.rb
class ZutatensController < ApplicationController
  before_action :set_zutaten, only: [:show, :edit, :update, :destroy]

        before_action :authenticate_user!, except: [:index, :show]

  # GET /zutatens
  # GET /zutatens.json
  def index 
    @zutatens = Zutaten.all.order("created_at desc")
  end

  # GET /zutatens/1
  # GET /zutatens/1.json
  def show
  end

  # GET /zutatens/new
  def new
    @zutaten = Zutaten.new
  end

  # GET /zutatens/1/edit
  def edit
  end

  # POST /zutatens
  # POST /zutatens.json
  def create
    @zutaten = Zutaten.new(zutaten_params)

    respond_to do |format|
      if @zutaten.save
        format.html { redirect_to @zutaten, notice: 'Zutaten was successfully created.' }
        format.json { render :show, status: :created, location: @zutaten }
      else
        format.html { render :new }
        format.json { render json: @zutaten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zutatens/1
  # PATCH/PUT /zutatens/1.json
  def update
    respond_to do |format|
      if @zutaten.update(zutaten_params)
        format.html { redirect_to @zutaten, notice: 'Zutaten was successfully updated.' }
        format.json { render :show, status: :ok, location: @zutaten }
      else
        format.html { render :edit }
        format.json { render json: @zutaten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zutatens/1
  # DELETE /zutatens/1.json
  def destroy
    @zutaten.destroy
    respond_to do |format|
      format.html { redirect_to zutatens_url, notice: 'Zutaten was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zutaten
      @zutaten = Zutaten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zutaten_params
      params.require(:zutaten).permit(:name, :preis,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/zutatens_helper.rb
module ZutatensHelper
end

app/views/home/about.html.erb
<h1>About</h1>
<p>Hi! We are Dustin and Franz, both students at the HTW Berlin.</p>

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>This is our Hoagie To-Go WebShop. Enjoy!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoagieWebShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>


  </head>

  <body>
    <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Hoagie To-Go Webshop</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", home_index_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "Customize Hoagie", orders_index_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "Reviews", reviews_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "About", home_about_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Login/Register", new_user_session_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      <%= yield(:header) %>
        <div class="container">
      <%= yield %>
      </div>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Customize your own Hoagie</h1>
<p>We deliver customized Hoagies right to your place.</p>

app/views/reviews/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @review, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

      

        <div class="field">
          <div class="control">
            <%= f.input :text, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Satisfaction</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :satisfaction, collection: Review::SATISFACTION, prompt: "Select how you liked it" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>
            
            
        

       
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', reviews_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Reviews
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', review: @review %>
</div>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.text %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Write a new Review
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', review: @review %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/zutatens/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @zutaten, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

      

        <div class="field">
          <div class="control">
            <%= f.input :text, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

            
        

       
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Lad ein Bild hoch</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Wähl deine Datei aus…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', reviews_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/zutatens/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Ingredients
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', zutaten: @zutaten %>
</div>

app/views/zutatens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zutatens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Preis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zutatens.each do |zutatens| %>
      <tr>
        <td><%= zutaten.name %></td>
        <td><%= zutaten.preis %></td>
        <td><%= link_to 'Show', zutaten %></td>
        <td><%= link_to 'Edit', edit_zutaten_path(zutaten) %></td>
        <td><%= link_to 'Destroy', zutaten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zutaten', new_zutaten_path %>

app/views/zutatens/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Add a new ingredient 
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', zutaten: @zutaten %>
</div>

app/views/zutatens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zutaten.name %>
</p>

<p>
  <strong>Preis:</strong>
  <%= @zutaten.preis %>
</p>

<%= link_to 'Edit', edit_zutaten_path(@zutaten) %> |
<%= link_to 'Back', zutatens_path %>